import type { ModeTheme } from "./types";

export const themes: Record<string, ModeTheme> = {
  engineer: {
    colors: {
      bg: "#0c0c0e",
      surface: "#141418",
      ink: "#f0ebe1",
      mute: "#8a8490",
      rule: "#2a2a32",
      accent: "#e8a020",
      accentDim: "#7a5510",
      gridColor: "rgba(255,255,255,0.025)",
    },
    fonts: {
      display: "'Space Grotesk', sans-serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "kinetic",
  },
  pm: {
    colors: {
      bg: "#efece4",
      surface: "#e8e5dd",
      ink: "#18181c",
      mute: "#6a6560",
      rule: "#d0ccc4",
      accent: "#2a4ad6",
      accentDim: "#c8d0f0",
      gridColor: "transparent",
    },
    fonts: {
      display: "'Space Grotesk', sans-serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 2,
    motion: "calm",
  },
  designer: {
    colors: {
      bg: "#f3efe3",
      surface: "#eae6da",
      ink: "#101830",
      mute: "#6a6a70",
      rule: "#ccc8bc",
      accent: "#b9342b",
      accentDim: "#f2c14e",
      gridColor: "rgba(0,0,0,0.03)",
    },
    fonts: {
      display: "'Fraunces', serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "calm",
  },
  data: {
    colors: {
      bg: "#fafaf7",
      surface: "#f4f4f0",
      ink: "#141414",
      mute: "#6a6a6a",
      rule: "#e0ddd4",
      accent: "#127a3c",
      accentDim: "#b0382a",
      gridColor: "rgba(0,0,0,0.04)",
    },
    fonts: {
      display: "'IBM Plex Serif', serif",
      body: "'DM Sans', sans-serif",
      mono: "'IBM Plex Mono', monospace",
    },
    radius: 0,
    motion: "calm",
  },
  everyday: {
    colors: {
      bg: "#f6f2e9",
      surface: "#ede9e0",
      ink: "#1a1a20",
      mute: "#7a7060",
      rule: "#d8d4c8",
      accent: "#8d6a3a",
      accentDim: "#c8b090",
      gridColor: "transparent",
    },
    fonts: {
      display: "'Instrument Serif', serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "off",
  },
  anime: {
    colors: {
      bg: "#fafaf7",
      surface: "#f0f0ed",
      ink: "#0a0a0a",
      mute: "#5a5a5a",
      rule: "#1a1a1a",
      accent: "#d7263d",
      accentDim: "#8a0010",
      gridColor: "transparent",
    },
    fonts: {
      display: "'Zen Kaku Gothic New', sans-serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "kinetic",
  },
  retro: {
    colors: {
      bg: "#8ed07d",
      surface: "#f6f0e5",
      ink: "#1c1b17",
      mute: "#575147",
      rule: "#2f2b23",
      accent: "#fb6f3c",
      accentDim: "#f3d36d",
      gridColor: "transparent",
    },
    fonts: {
      display: "'Space Grotesk', sans-serif",
      body: "'DM Sans', sans-serif",
      mono: "'IBM Plex Mono', monospace",
    },
    radius: 0,
    motion: "kinetic",
  },
  pdf: {
    colors: {
      bg: "#ffffff",
      surface: "#f5f5f5",
      ink: "#111111",
      mute: "#888888",
      rule: "#dddddd",
      accent: "#444444",
      accentDim: "#999999",
      gridColor: "transparent",
    },
    fonts: {
      display: "'Georgia', serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "off",
  },
  codebase: {
    colors: {
      bg: "#1e1e1e",
      surface: "#252526",
      ink: "#d4d4d4",
      mute: "#6a6a6a",
      rule: "#3e3e42",
      accent: "#569cd6",
      accentDim: "#264f78",
      gridColor: "transparent",
    },
    fonts: {
      display: "'JetBrains Mono', monospace",
      body: "'JetBrains Mono', monospace",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "calm",
  },
  director: {
    colors: {
      bg: "#111009",
      surface: "#1c1810",
      ink: "#ede4cf",
      mute: "#7a6a4a",
      rule: "#2c2418",
      accent: "#c8902a",
      accentDim: "#5a3e10",
      gridColor: "transparent",
    },
    fonts: {
      display: "'Fraunces', serif",
      body: "'DM Sans', sans-serif",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "kinetic",
  },
  signal: {
    colors: {
      bg: "#060a08",
      surface: "#0c110e",
      ink: "#d4ffe6",
      mute: "#3a6049",
      rule: "#132318",
      accent: "#00e87a",
      accentDim: "#005c30",
      gridColor: "rgba(0,232,122,0.035)",
    },
    fonts: {
      display: "'JetBrains Mono', monospace",
      body: "'JetBrains Mono', monospace",
      mono: "'JetBrains Mono', monospace",
    },
    radius: 0,
    motion: "kinetic",
  },
  pdfDark: {
    colors: {
      bg: "#1c1c1c",
      surface: "#252525",
      ink: "#e2e2e2",
      mute: "#888888",
      rule: "#333333",
      accent: "#aaaaaa",
      accentDim: "#555555",
      gridColor: "transparent",
    },
    fonts: {
      display: "'IBM Plex Mono', monospace",
      body: "'IBM Plex Mono', monospace",
      mono: "'IBM Plex Mono', monospace",
    },
    radius: 0,
    motion: "off",
  },
};
